[project]
name = "ui-layout"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx[http2]>=0.28.1",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
layout = "ui.main:main"

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff"]

[tool.uv]
package = true

[tool.setuptools]
packages = ["ui"]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--cov=ui --cov-report=term-missing"
log_cli = true
log_cli_level = "INFO"
log_level = "DEBUG"

[tool.coverage.run]
source = ["ui"]
omit = [
    "ui/logger.py",
    "ui/main.py",
    "ui/render.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]

[dependency-groups]
dev = [
    "isort>=8.0.1",
]
